import type { Metadata } from 'next'
import Script from 'next/script'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import DailyTips from '@/components/DailyTips'
import ProgressBar from '@/components/ProgressBar'
import ToolsShowcase from '@/components/ToolsShowcase'
import Breadcrumb from '@/components/Breadcrumb'
import RelatedTools from '@/components/RelatedTools'
import ToolJsonLd from '@/components/ToolJsonLd'
import SkipToContent from '@/components/SkipToContent'
import ToolTracker from '@/components/ToolTracker'
import ToolShareButton from '@/components/ToolShareButton'
import BackToTop from '@/components/BackToTop'
import MobileBottomNav from '@/components/MobileBottomNav'
import ErrorBoundary from '@/components/ErrorBoundary'
import { LanguageProvider } from '@/contexts/LanguageContext'
import I18nWrapper from '@/components/I18nWrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  metadataBase: new URL('https://toolhub.ai.kr'),
  title: {
    default: '툴허브 - 연봉, 대출, 시간변환 계산기 | 무료 온라인 도구',
    template: '%s | 툴허브'
  },
  description: '연봉 실수령액, 대출 상환, 적금 이자, 시간변환까지! 금융계산기부터 개발자 도구까지 모든 계산을 한 곳에서 해결하세요.',
  keywords: '툴허브, 계산기, 연봉계산기, 대출계산기, 적금계산기, 시간변환기, 타임존변환, Unix타임스탬프, 실수령액계산, 정규식추출기, JSON 포맷터, SQL 포맷터, Markdown 뷰어, 바코드 생성기, QR코드 생성기, 온라인도구, 무료계산기, 개발자도구',
  authors: [{ name: '툴허브' }],
  creator: '툴허브',
  publisher: '툴허브',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  manifest: '/manifest.json',
  icons: {
    icon: [
      { url: '/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
      { url: '/favicon-96x96.png', sizes: '96x96', type: 'image/png' }
    ],
    apple: [
      { url: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' }
    ],
    other: [
      { rel: 'mask-icon', url: '/safari-pinned-tab.svg', color: '#2563eb' }
    ]
  },
  openGraph: {
    type: 'website',
    locale: 'ko_KR',
    url: 'https://toolhub.ai.kr',
    siteName: '툴허브',
    title: '툴허브 - 필수 계산기와 개발자 도구 모음',
    description: '연봉, 대출, 시간변환부터 바코드 생성, JSON 포맷터까지 모든 계산을 한 곳에서 해결하세요',
    images: [
      {
        url: 'https://toolhub.ai.kr/og-image-1200x630.png',
        width: 1200,
        height: 630,
        alt: '툴허브 - 온라인 계산기와 개발자 도구 모음',
      },
      {
        url: 'https://toolhub.ai.kr/og-image-600x315.png',
        width: 600,
        height: 315,
        alt: '툴허브 - 온라인 계산기와 개발자 도구 모음',
      }
    ],
  },
  twitter: {
    card: 'summary_large_image',
    site: '@toolhub_kr',
    creator: '@toolhub_kr',
    title: '툴허브 - 필수 계산기와 개발자 도구 모음',
    description: '연봉, 대출, 시간변환부터 바코드 생성까지 모든 계산을 한 곳에서',
    images: ['https://toolhub.ai.kr/og-image-1200x630.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  // verification: { google: 'xxx' }, // Google Search Console 인증 후 실제 코드 입력
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const adsenseId = process.env.NEXT_PUBLIC_ADSENSE_ID || 'ca-pub-2070759131396958'
  const cfAnalyticsToken = process.env.NEXT_PUBLIC_CF_ANALYTICS_TOKEN

  return (
    <html lang="ko">
      <head suppressHydrationWarning>
        <meta name="google-adsense-account" content={adsenseId} />
        <meta name="naver-site-verification" content="8cdcacf38562d4fa1ee11f4f77a8a0f15f11d532" />
        
        {/* OG/Twitter tags are generated by Next.js metadata export above */}

        {/* Additional SEO Meta Tags */}
        <meta name="color-scheme" content="light dark" />
        <meta name="theme-color" content="#2563eb" media="(prefers-color-scheme: light)" />
        <meta name="theme-color" content="#111827" media="(prefers-color-scheme: dark)" />
        <meta name="msapplication-TileColor" content="#2563eb" />
        <meta name="msapplication-TileImage" content="/android-chrome-192x192.png" />
        <meta name="application-name" content="툴허브" />
        <meta name="apple-mobile-web-app-title" content="툴허브" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="mobile-web-app-capable" content="yes" />
        
        {/* Preconnect for performance */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://pagead2.googlesyndication.com" />
        
        {/* DNS Prefetch */}
        <link rel="dns-prefetch" href="//pagead2.googlesyndication.com" />

        {/* hreflang - same URL for all languages (client-side i18n) */}
        <link rel="alternate" hrefLang="x-default" href="https://toolhub.ai.kr" />
        
        {/* AdSense Script in Head */}
        {adsenseId && (
          <script
            async
            src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${adsenseId}`}
            crossOrigin="anonymous"
          />
        )}
      </head>
      <body className={`${inter.className} min-h-screen bg-white dark:bg-gray-900`}>
        {/* Axeptio Cookie Consent Script with Google Consent Mode */}
        <Script
          id="axeptio-settings"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.axeptioSettings = {
                clientId: "6852548e237197d2502e4208",
                cookiesVersion: "toolhub-en-EU-2",
                googleConsentMode: {
                  default: {
                    analytics_storage: "denied",
                    ad_storage: "denied",
                    ad_user_data: "denied",
                    ad_personalization: "denied",
                    wait_for_update: 500
                  }
                }
              };
            `
          }}
        />
        <Script
          id="axeptio-sdk"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function(d, s) {
                var t = d.getElementsByTagName(s)[0], e = d.createElement(s);
                e.async = true;
                e.src = "//static.axept.io/sdk.js";
                t.parentNode.insertBefore(e, t);
              })(document, "script");
            `
          }}
        />
        <LanguageProvider>
          <I18nWrapper>
            <SkipToContent />
            <ProgressBar />
            <ToolTracker />
            <Header />
            {/* Breadcrumb Navigation */}
            <Breadcrumb />
            {/* Per-tool JSON-LD structured data */}
            <ToolJsonLd />
            {/* Main Content */}
            <main id="main-content" className="pb-16 md:pb-0">
              <ErrorBoundary>
                {children}
              </ErrorBoundary>
            </main>

            {/* Social Share FAB + Back to Top */}
            <ToolShareButton />
            <BackToTop />

            {/* Related Tools */}
            <RelatedTools />

            {/* Tools Showcase - Common across all pages */}
            <ToolsShowcase />

            {/* Footer */}
            <Footer />

            {/* Mobile Bottom Navigation */}
            <MobileBottomNav />

            {/* Daily Tips Component */}
            <DailyTips />
          </I18nWrapper>

        </LanguageProvider>
        
        {/* Service Worker Registration for PWA */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              if ('serviceWorker' in navigator) {
                window.addEventListener('load', function() {
                  navigator.serviceWorker.register('/sw.js')
                    .then(function(registration) {
                      registration.addEventListener('updatefound', function() {
                        var newWorker = registration.installing;
                        if (newWorker) {
                          newWorker.addEventListener('statechange', function() {
                            if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
                              var toast = document.createElement('div');
                              toast.innerHTML = '<div style="position:fixed;bottom:24px;right:24px;z-index:9999;background:#1e40af;color:#fff;padding:16px 20px;border-radius:12px;box-shadow:0 4px 24px rgba(0,0,0,0.2);display:flex;align-items:center;gap:12px;font-size:14px;font-family:sans-serif;max-width:360px;animation:slideUp .3s ease"><span>새 버전이 있습니다</span><button onclick="window.location.reload()" style="background:#fff;color:#1e40af;border:none;padding:6px 14px;border-radius:6px;cursor:pointer;font-weight:600;font-size:13px;white-space:nowrap">업데이트</button><button onclick="this.closest(\'div\').parentElement.remove()" style="background:none;border:none;color:#93c5fd;cursor:pointer;font-size:18px;padding:0 4px">✕</button></div>';
                              document.body.appendChild(toast);
                            }
                          });
                        }
                      });
                    })
                    .catch(function() {});
                });

                // Listen for app install prompt
                var deferredPrompt;
                window.addEventListener('beforeinstallprompt', function(event) {
                  event.preventDefault();
                  deferredPrompt = event;
                  var installButton = document.getElementById('install-button');
                  if (installButton) {
                    installButton.style.display = 'block';
                    installButton.addEventListener('click', function() {
                      deferredPrompt.prompt();
                      deferredPrompt.userChoice.then(function(choiceResult) {
                        deferredPrompt = null;
                      });
                    });
                  }
                });

                // Handle app installed
                window.addEventListener('appinstalled', function(event) {
                  // Hide install button
                  const installButton = document.getElementById('install-button');
                  if (installButton) {
                    installButton.style.display = 'none';
                  }
                });
              }
            `,
          }}
        />
        
        {/* Cloudflare Web Analytics */}
        {cfAnalyticsToken && (
          <script
            defer
            src="https://static.cloudflareinsights.com/beacon.min.js"
            data-cf-beacon={`{"token":"${cfAnalyticsToken}"}`}
          />
        )}
      </body>
    </html>
  )
}