/**
 * 도구 아이콘 (단색 라인 아이콘, lucide). menuConfig의 emoji `icon`은 레거시/OG용으로만 남음.
 * 화면에는 <ToolIcon href=... /> 로 표시. 새 도구 추가 시 여기에 한 줄 추가 (없으면 카테고리 기본 아이콘).
 */
import type { LucideIcon } from 'lucide-react'
import {
  Wallet, Scale, Table2, Landmark, PiggyBank, CandlestickChart, Briefcase, Building2, Receipt, ArrowLeftRight,
  House, Building, Car, CarFront, Fuel, TrendingDown, Percent, Cake, GraduationCap, TrendingUp, Zap, Tag, Ruler,
  FileText, Droplet, Coins, Umbrella, Flame, CarTaxiFront, CreditCard, Package, SquareParking, UtensilsCrossed,
  CalendarRange, Truck, Wrench, Gift, PaintRoller, LineChart, FileSearch, Clock, Medal, Ticket, BarChart3,
  ShoppingCart, Monitor, Baby, HeartPulse, Heart, Target, BatteryCharging, ShieldCheck, Regex, Braces, FileCode,
  Network, Code, KeyRound, Fingerprint, CalendarClock, QrCode, ScanBarcode, Database, PenLine, Box, Type, Binary,
  Link, Hash, GitCompare, Palette, AlignLeft, CaseSensitive, Lock, CalendarDays, Dices, Timer, NotebookPen,
  Smartphone, Smile, Moon, Globe, Keyboard, Languages, ScanLine, Clock3, Blend, BadgeCheck, Volume2, Radio,
  IdCard, MonitorCheck, Contrast, Square, Camera, LayoutGrid, PenTool, Plug, Image, Gauge, Stamp, Pilcrow,
  Presentation, Mail, MessageSquareText, GanttChart, FileSpreadsheet, SquareKanban, ClipboardList, Settings2,
  Terminal, FileLock, History, Eye, MonitorSmartphone, Workflow, Shuffle, Cpu, BookOpen, MessagesSquare, Layers,
  Puzzle, Map, Crop, Images, Pipette, Grid3x3, ScanText, Signature, FileType, Activity, Compass, Music, Waves,
  Minimize2, Video, Mic, Film, Scissors, Download, Apple, Dumbbell, Wine, Stethoscope, Wind, BedDouble, Salad,
  NotebookText, Brain, HeartHandshake, Users, Flower2, BookOpenCheck, Hexagon, Gamepad2, CircleDot, Circle,
  Grid2x2, Crown, Ship, Spline, Hand, Rows3, Bomb, LayoutPanelTop, Swords, Blocks, Spade, Bird, Ghost,
  SquareDashed, Calculator, Server, ListChecks, Gem, Bot, Home, Sigma, SquareStack, Newspaper, CircleHelp, Disc3,
} from 'lucide-react'
import type { CategoryKey } from './menuConfig'

export const toolIcons: Record<string, LucideIcon> = {
  // 금융/생활 계산기
  '/salary-calculator': Wallet,
  '/salary-comparison': Scale,
  '/salary-table': Table2,
  '/loan-calculator': Landmark,
  '/savings-calculator': PiggyBank,
  '/stock-calculator': CandlestickChart,
  '/retirement-calculator': Briefcase,
  '/national-pension': Building2,
  '/tax-calculator': Receipt,
  '/exchange-calculator': ArrowLeftRight,
  '/real-estate-calculator': House,
  '/monthly-rent-subsidy': Building,
  '/bogeumjari-loan': Home,
  '/car-loan-calculator': Car,
  '/car-tax-calculator': CarFront,
  '/fuel-calculator': Fuel,
  '/median-income': TrendingDown,
  '/percent-calculator': Percent,
  '/age-calculator': Cake,
  '/gpa-calculator': GraduationCap,
  '/compound-calculator': TrendingUp,
  '/electricity-calculator': Zap,
  '/discount-calculator': Tag,
  '/pyeong-calculator': Ruler,
  '/vat-calculator': FileText,
  '/rent-converter': ArrowLeftRight,
  '/water-bill': Droplet,
  '/hourly-wage': Coins,
  '/severance-pay': Briefcase,
  '/annual-leave': Umbrella,
  '/gas-bill': Flame,
  '/taxi-fare': CarTaxiFront,
  '/installment-calculator': CreditCard,
  '/shipping-calculator': Package,
  '/parking-fee': SquareParking,
  '/dutch-pay': UtensilsCrossed,
  '/budget-calculator': Wallet,
  '/loan-schedule': CalendarRange,
  '/moving-cost': Truck,
  '/car-maintenance': Wrench,
  '/inheritance-gift-tax': Gift,
  '/freelancer-tax': Briefcase,
  '/pension-calculator': Landmark,
  '/interior-calculator': PaintRoller,
  '/investment-calculator': LineChart,
  '/unemployment-benefit': FileSearch,
  '/weekly-holiday-pay': Clock,
  '/housing-subscription': Building2,
  '/capital-gains-tax': Building,
  '/military-discharge': Medal,
  '/year-end-tax': Receipt,
  '/income-tax': FileText,
  '/lotto-tax': Ticket,
  '/salary-rank': BarChart3,
  '/jeonse-loan': House,
  '/dsr-calculator': Gauge,
  '/margin-calculator': TrendingUp,
  '/sales-commission': ShoppingCart,
  '/acquisition-tax': Building,
  '/average-calculator': Sigma,
  '/grade-calculator': GraduationCap,
  '/gpa-converter': ArrowLeftRight,
  '/pc-electricity': Monitor,
  '/parental-leave': Baby,
  '/health-insurance': HeartPulse,
  '/wedding-calculator': Heart,
  '/comprehensive-property-tax': Building2,
  '/cagr-calculator': TrendingUp,
  '/tax-season': ClipboardList,
  '/bonus-calculator': Target,
  '/government-subsidy': Landmark,
  '/youth-rent-subsidy': Home,
  '/ev-subsidy': BatteryCharging,
  '/child-benefit': Baby,
  '/jeonse-checklist': ShieldCheck,

  // 개발/유틸리티
  '/regex-extractor': Regex,
  '/time-converter': Clock3,
  '/json-formatter': Braces,
  '/json-xml-converter': FileCode,
  '/yaml-json-converter': FileCode,
  '/subnet-calculator': Network,
  '/html-entity-converter': Code,
  '/json-csv-converter': FileSpreadsheet,
  '/jwt-decoder': KeyRound,
  '/uuid-generator': Fingerprint,
  '/cron-tester': CalendarClock,
  '/qr-generator': QrCode,
  '/barcode-generator': ScanBarcode,
  '/sql-formatter': Database,
  '/markdown-editor': PenLine,
  '/3d-viewer': Box,
  '/character-counter': Type,
  '/base64-converter': Binary,
  '/url-encoder': Link,
  '/hash-generator': Hash,
  '/diff-viewer': GitCompare,
  '/color-converter': Palette,
  '/lorem-ipsum': AlignLeft,
  '/unit-converter': Ruler,
  '/text-converter': CaseSensitive,
  '/password-generator': Lock,
  '/dday-calculator': CalendarDays,
  '/random-picker': Dices,
  '/timer': Timer,
  '/base-converter': Binary,
  '/notepad': NotebookPen,
  '/screen-info': MonitorSmartphone,
  '/emoji-picker': Smile,
  '/lunar-converter': Moon,
  '/ip-checker': Globe,
  '/typing-test': Keyboard,
  '/number-to-korean': Languages,
  '/qr-scanner': ScanLine,
  '/font-preview': Type,
  '/world-clock': Globe,
  '/css-gradient': Blend,
  '/korean-syllable': Languages,
  '/roman-numeral': Hash,
  '/business-number': BadgeCheck,
  '/color-palette': Palette,
  '/aspect-ratio': Crop,
  '/text-to-speech': Volume2,
  '/morse-code': Radio,
  '/resident-number': IdCard,
  '/monitor-test': MonitorCheck,
  '/keyboard-converter': Keyboard,
  '/contrast-checker': Contrast,
  '/box-shadow': Square,
  '/code-screenshot': Camera,
  '/flexbox-grid': LayoutGrid,
  '/svg-editor': PenTool,
  '/api-tester': Plug,
  '/favicon-generator': Image,
  '/pomodoro': Timer,
  '/css-unit-converter': Ruler,
  '/speed-test': Gauge,
  '/stamp-generator': Stamp,
  '/fancy-text': Pilcrow,
  '/presentation-timer': Presentation,
  '/chart-studio': BarChart3,
  '/email-template': Mail,
  '/prompt-generator': MessageSquareText,
  '/gantt-chart': GanttChart,
  '/invoice-generator': FileSpreadsheet,
  '/kanban-board': SquareKanban,
  '/meeting-minutes': ClipboardList,
  '/crontab-generator': CalendarClock,
  '/regex-builder': Regex,
  '/env-editor': Settings2,
  '/llm-token-calculator': Bot,
  '/webserver-config': Server,
  '/curl-builder': Terminal,
  '/chmod-calculator': FileLock,
  '/http-status': Globe,
  '/port-reference': Plug,
  '/linux-command': Terminal,
  '/calculation-history': History,
  '/color-blindness-simulator': Eye,
  '/screen-compare': Smartphone,
  '/algorithm': Workflow,
  '/order-picker': Shuffle,
  '/menu-roulette': UtensilsCrossed,
  '/menu-picker': UtensilsCrossed,
  '/roulette': Disc3,
  '/team-divider': Users,
  '/lottery-draw': Ticket,
  '/coin-flip': Coins,
  '/dice-roller': Dices,
  '/random-number': Hash,
  '/yes-no': CircleHelp,
  '/rock-paper-scissors': Hand,
  '/penalty-roulette': Target,
  '/cs-visualizer': Cpu,
  '/cs-quiz': ListChecks,
  '/cs-dictionary': BookOpen,
  '/cs-interview': MessagesSquare,
  '/cs-hub': GraduationCap,
  '/dev-cheatsheet': Newspaper,
  '/system-design': Layers,
  '/coding-patterns': Puzzle,
  '/dev-roadmap': Map,

  // 이미지/미디어
  '/image-resizer': Crop,
  '/image-editor': PenTool,
  '/image-converter': Images,
  '/color-extractor': Pipette,
  '/image-mosaic': Grid3x3,
  '/image-watermark': Droplet,
  '/image-ocr': ScanText,
  '/signature-generator': Signature,
  '/pdf-tools': FileType,
  '/noise-meter': Activity,
  '/spirit-level': Compass,
  '/metronome': Music,
  '/white-noise': Waves,
  '/image-compressor': Minimize2,
  '/screen-recorder': Video,
  '/voice-memo': Mic,
  '/gif-maker': Film,
  '/background-remover': Scissors,
  '/collage-maker': LayoutPanelTop,
  '/image-scraper': Download,

  // 건강
  '/bmi-calculator': Scale,
  '/calorie-calculator': Apple,
  '/body-fat-calculator': Dumbbell,
  '/work-hours-calculator': Clock,
  '/alcohol-calculator': Wine,
  '/due-date': Baby,
  '/blood-pressure': Stethoscope,
  '/exercise-calorie': Flame,
  '/breathing-exercise': Wind,
  '/blood-sugar': Droplet,
  '/sleep-calculator': BedDouble,
  '/nutrition-calculator': Salad,
  '/meal-diary': NotebookText,
  '/biorhythm': Waves,
  '/mbti-test': Brain,
  '/mbti-compatibility': HeartHandshake,
  '/name-compatibility': Users,
  '/personal-color': Palette,
  '/ovulation-calculator': Flower2,
  '/csat-grade': BookOpenCheck,
  '/enneagram': Hexagon,

  // 게임
  '/games': Gamepad2,
  '/omok': CircleDot,
  '/othello': Circle,
  '/connect4': Grid2x2,
  '/checkers': Crown,
  '/mancala': SquareStack,
  '/battleship': Ship,
  '/dots-and-boxes': SquareDashed,
  '/chess': Swords,
  '/snake-game': Spline,
  '/2048': Grid2x2,
  '/memory-game': Spade,
  '/reaction-test': Zap,
  '/color-blind-test': Eye,
  '/lotto-generator': Dices,
  '/ladder-game': Rows3,
  '/minesweeper': Bomb,
  '/sudoku': Grid3x3,
  '/tetris': Blocks,
  '/number-baseball': Target,
  '/korean-wordle': Type,
  '/breakout-game': Blocks,
  '/solitaire': Spade,
  '/15-puzzle': Puzzle,
  '/flappy-bird': Bird,
  '/hangman': Hand,
  '/pac-man': Ghost,
  '/picross': Grid3x3,
  '/mahjong-solitaire': Gem,
  '/crossword': Type,
}

export const categoryIcons: Record<CategoryKey, LucideIcon> = {
  calculators: Calculator,
  tools: Code,
  media: Image,
  health: HeartPulse,
  games: Gamepad2,
}

